<a href="https://colab.research.google.com/github/ander002/DeepLearning/blob/main/DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 入门pytorch

## 基本操作

In [ ]:
import torch
x = torch.arange(12) #创建的一个行向量[0,12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape #访问张量的形状

torch.Size([12])

In [ ]:
x.numel()  #一个张量中元素的总数

12

In [ ]:
X = x.reshape(3, 4)  #改变形状，不改变元素数量和值
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros(2, 3, 4) #生成全0矩阵 torch.ones(2, 3, 4,2)这是全1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.randn(3, 4) #随机创建一个（3，4）的张量，其中每个元素都从均值0、标准差为1的标准高斯分布中随机取样

tensor([[ 0.3303, -0.0402,  0.3889, -0.5177],
        [ 0.0255,  0.0956, -1.1163, -0.6623],
        [-0.8355, -0.9201, -0.8355, -0.9374]])

In [ ]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])  #提供python列表（嵌套列表）来为张量中的元素赋值，这里外层的列表对应0轴，内层对应1轴

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 运算

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y,x - y, x * y,x / y,x ** y,torch.exp(x) # 元素对应运算，** 是求幂运算,

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]),
 tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]))

In [ ]:
import torch
X = torch.arange(12,dtype = torch.float32).reshape(3,4)  #reshape((3,4))?????
Y = torch.tensor([[2.0, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])
torch.cat((X,Y),dim=0), torch.cat((X,Y),dim=1) #把多个张量连接在一起，dim=0，按0轴链接就是按行堆积，行数增加，dim=1，按1轴链接就是按列拼接，列数增加

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X == Y  #通过逻辑运算符构建张量

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum() #对张量中所有元素进行求和，产生一个元素的张量

tensor(66.)

In [ ]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2)) #广播机制
a, b 

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [ ]:
a + b  #形状不匹配的矩阵相加，广播机制将两个矩阵广播为一个更大的3x2矩阵，矩阵a将复制列，矩阵b将复制行

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
X[-1],X[1:3] #张量可以通过索引访问，与python一样，第一个元素的索引是0，负号表示从列表尾部相对应的元素，-1代表最后一行元素，[1:3]的意思是选择第二个和第三个元素，这里是指第二行和第三行。

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
X[1, 2] = 9    #修改指定元素
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[0:2, :] = 12   #批量修改元素值，这里指的是第[0,2)行，和所有列修改为12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before  #这表示python是先计算Y+X然后把Y指向新地址，这样做有两个弊端，第一，我们不想让他经常分配新内存，第二，分配新内存后，旧内存依然是我们旧的参数，很有可能某次调参的时候就会指向无用的旧内存

False

In [ ]:
Z = torch.zeros_like(Y)
print(f'id(Z):{id(Z)}')
Z[:] = X + Y          #执行原地操作非常简单，我们可以使用切片表示法，将操作的结果分配给先前分配的数组。
print(f'id(Z):{id(Z)}')

id(Z):140137726682608
id(Z):140137726682608


In [ ]:
before = id(X)
X += Y   #如果之后没有用X的话可以X[:] = X+Y或者X+=Y来减少内存开销
id(X) == before

True

In [ ]:
A = X.numpy()    #转换python对象
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])    #将大小为1的张量转换为python 标量，可以用item。
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理

In [ ]:
import os 
os.makedirs(os.path.join('..', 'data'), exist_ok=True)  #创建人工数据集
data_file = os.path.join('..', 'data', 'house_tiny.csv') 
with open(data_file, 'w') as f: 
  f.write('NumRooms,Alley,Price\n') # 列名 
  f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本 
  f.write('2,NA,106000\n') 
  f.write('4,NA,178100\n') 
  f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd

data = pd.read_csv(data_file)  #读取数据，其中有许多缺失值，我们要处理缺失值，有插值和删除两种解决，我们用插值
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]     #iloc是位置索引，inputs是data的前两列，outputs是data的最后一列
inputs = inputs.fillna(inputs.mean())    #fillna函数是若存在缺失值，用参数代替，这里我们用平均数代替
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
inputs = pd.get_dummies(inputs,dummy_na=True)    #由于我们Alley的值只有NaN和Pave两种，所以我们可以吧Alley分为两列Alley_Pave和Alley_nan
print(inputs)                                    #其中Alley值为Pave，则Alley_Pave的值为1，反之为0，Alley_nan同理。

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
import torch

X,y = torch.tensor(inputs.values),torch.tensor(outputs.values)     #将inputs和outputs转换为张量，
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

### 练习

#### 创建包含更多行和列的原始数据集
1. 删除缺失值最多的列
2. 将预处理数据集转换为张量格式

In [3]:
import os 
os.makedirs(os.path.join('..', 'data'), exist_ok=True)  #创建人工数据集
data_files = os.path.join('..', 'data', 'houses_tiny.csv') 
with open(data_files, 'w') as f: 
  f.write('NumRooms,Alley,Price\n') # 列名 
  f.write('NA,Pave,127500\n') # 每⾏表⽰⼀个数据样本 
  f.write('2,NA,106000\n') 
  f.write('4,NA,178100\n') 
  f.write('NA,NA,140000\n')
  f.write('NA,Pave,143430\n')
  f.write('6,NA,190000\n')
  f.write('3,NA,150000\n')

In [4]:
import pandas as pd

data = pd.read_csv(data_files)  #读取数据，其中有许多缺失值，我们要处理缺失值，有插值和删除两种解决，在这里我们用删除
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000
4       NaN  Pave  143430
5       6.0   NaN  190000
6       3.0   NaN  150000

In [5]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]

inputs = inputs.dropna(axis=1,thresh=(inputs.count().min()+1))   #dropna函数，其中axis=1是删除有缺失值的列，thresh参数是保留至少有n个非NaN数据的行/列
num = inputs.count() # count函数计算非nan元素的数量
inputs = inputs.fillna(inputs.mean())
inputs,outputs

(   NumRooms
 0      3.75
 1      2.00
 2      4.00
 3      3.75
 4      3.75
 5      6.00
 6      3.00, 0    127500
 1    106000
 2    178100
 3    140000
 4    143430
 5    190000
 6    150000
 Name: Price, dtype: int64)

In [6]:
import torch
W,z = torch.tensor(inputs.values),torch.tensor(outputs.values)  #转换为张量
W,z

(tensor([[3.7500],
         [2.0000],
         [4.0000],
         [3.7500],
         [3.7500],
         [6.0000],
         [3.0000]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000, 143430, 190000, 150000]))

# 线性代数

In [7]:
import torch

x = torch.tensor([3.0])  #标量用只有一个元素的张量表示
y = torch.tensor([2.0])

x + y,x * y,x / y,x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [ ]:
x = torch.arange(4)  #我们用一维张量处理向量，问题如何区分行向量或列向量？
x

tensor([0, 1, 2, 3])

In [ ]:
l = x.reshape(4, 1)  #列向量
h = x.reshape(1,4)   #行向量
l,h

(tensor([[0],
         [1],
         [2],
         [3]]), tensor([[0, 1, 2, 3]]))

In [ ]:
x[3]  #通过索引访问任一元素

tensor(3)

In [ ]:
len(x)  #张量长度
x.shape  #张量形状  某个轴的维数就是这个轴的长度

torch.Size([4])

In [ ]:
A = torch.arange(20).reshape(5,4)  #矩阵
A,A.T  #A的转置

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]), tensor([[ 0,  4,  8, 12, 16],
         [ 1,  5,  9, 13, 17],
         [ 2,  6, 10, 14, 18],
         [ 3,  7, 11, 15, 19]]))

In [ ]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])  #对称矩阵
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [ ]:
X = torch.arange(24).reshape(2,3,4)  #三维张量
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [8]:
A = torch.arange(20,dtype= torch.float32).reshape(5,4)
B = A.clone()
A,A + B   #形状相同的张量，四则运算后的形状不变

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [9]:
A * B #两张量按元素相乘叫哈达玛积，对应元素相乘

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [11]:
a = 2
X = torch.arange(24).reshape(2,3,4)  #标量加上或乘上一个张量不会改变形状，其中标量是对张量中每一个元素做运算
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

In [14]:
x = torch.arange(4,dtype=torch.float32)  #计算向量元素的总和，用sum（）
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [15]:
A.shape,A.sum()  #表示任一张量的形状和元素和。

(torch.Size([5, 4]), tensor(190.))

In [16]:
A_sum_axis0 = A.sum(axis = 0)    #可以通过指定一个轴来通过求和降低维度，这里指定的是0轴，也就是行，求和降维之后变成向量
A_sum_axis0, A_sum_axis0.shape   #也就是说，指定哪一个轴哪一轴就消失。

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [17]:
A_sum_axis1 = A.sum(axis= 1)
A_sum_axis1,A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [18]:
A.sum(axis=[0,1])  #相当于对矩阵所有元素求和。<===>A.sum()

tensor(190.)

In [22]:
A.mean(),A.sum()/A.numel()   #求平均值

(tensor(9.5000), tensor(9.5000))

In [24]:
A.mean(axis=1),A.sum(axis=1)/A.shape[1]  #指定轴求平均值可以指定轴降低张量维度

(tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000]))